name: Docker Build/Publish Image

on:
    workflow_dispatch:
    push:
    # branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            DOCKER_REGISTRY:
            DOCKER_IMAGE: kolebarnes/von-image
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_TARGET_PLATFORM: linux/arm/v7

        steps:
            - name: Checkout the code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              id: buildx
              uses: crazy-max/ghaction-docker-buildx@v3
              with:
                  buildx-version: latest
                  qemu-version: latest

            - name: Available platforms
              run: echo ${{ steps.buildx.outputs.platforms }}

            - name: Docker Login
              if: success()
              run: |
                  docker login ${DOCKER_REGISTRY} --username "${DOCKER_USERNAME}" --password '${{ secrets.DOCKER_PASSWORD }}'

            - name: Build and push image
              if: success()
              run: |
                  python3 make_image.py 1.15.0 --py37 --name ${DOCKER_IMAGE} --push  --buildx --platform ${DOCKER_TARGET_PLATFORM}
